import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "transparent",
    alignItems: "center",
    paddingTop: 0,
    paddingBottom: 16,
    paddingHorizontal: 20,
    zIndex: 1,
  },
  infoBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
    borderRadius: 999,
    backgroundColor: "rgba(255, 250, 250, 0.58)",
    borderWidth: 1,
    borderColor: "rgba(110, 23, 23, 0.08)",
    shadowColor: "#6E1717",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  infoText: {
    color: "#6A1A1A",
    fontSize: 17,
    textAlign: "center",
    fontWeight: "600",
    fontFamily: "Inter",
    letterSpacing: 0.2,
    textShadowColor: "rgba(255, 255, 255, 0.35)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  toggleContainer: {
    width: "100%",
    maxWidth: 360,
    position: "relative",
    flexDirection: "row",
    alignItems: "center",
    padding: 6,
    borderRadius: 999,
    backgroundColor: "rgba(139, 32, 32, 0.7)",
    shadowColor: "#8b2020",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 4,
  },
  activeIndicator: {
    position: "absolute",
    top: 6,
    bottom: 6,
    left: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    shadowColor: "#6E1717",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  toggleOption: {
    flex: 1,
    minHeight: 54,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
  },
  toggleLabel: {
    fontSize: 22,
    fontWeight: "700",
    fontFamily: "Inter",
  },
});

export default styles;
